# Generated by Django 5.2.4 on 2025-07-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RevenueReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("website_name", models.CharField(max_length=255)),
                (
                    "revenue_monthly",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "revenue_yearly",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
