# Generated by Django 5.2.4 on 2025-07-06 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playbooks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="playbook",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="playbook",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playbooks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="playbook",
            name="category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="playbook",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="playbook",
            name="download_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playbook",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playbook",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="playbook",
            name="tags",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="playbook",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="playbook",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="playbook",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="playbooks/"),
        ),
    ]
