# Generated by Django 5.2.4 on 2025-07-06 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tool",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="tool",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tools",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tool",
            name="category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="tool",
            name="click_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tool",
            name="documentation_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="tool",
            name="icon",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="tool",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tool",
            name="is_free",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tool",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="tool",
            name="pricing_model",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="tool",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="tool",
            name="review_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tool",
            name="tags",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="tool",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
